export interface EmojiEntry {
  shortcode: string;
  emoji: string;
  tags?: string[];
}

/** GitHub-style shortcodes — used for picker + `:name` autocomplete */
export const EMOJI_CATALOG: EmojiEntry[] = [
  { shortcode: 'sparkles', emoji: '✨', tags: ['stars', 'magic'] },
  { shortcode: 'point_right', emoji: '👉', tags: ['finger', 'hand'] },
  { shortcode: 'point_left', emoji: '👈', tags: ['finger', 'hand'] },
  { shortcode: 'point_up', emoji: '☝️', tags: ['finger', 'hand'] },
  { shortcode: 'point_down', emoji: '👇', tags: ['finger', 'hand'] },
  { shortcode: 'fire', emoji: '🔥', tags: ['hot', 'lit'] },
  { shortcode: 'white_check_mark', emoji: '✅', tags: ['done', 'yes'] },
  { shortcode: 'x', emoji: '❌', tags: ['no', 'cross'] },
  { shortcode: 'bulb', emoji: '💡', tags: ['idea', 'light'] },
  { shortcode: 'rocket', emoji: '🚀', tags: ['launch', 'ship'] },
  { shortcode: 'star2', emoji: '🌟', tags: ['star', 'glow'] },
  { shortcode: 'star', emoji: '⭐', tags: ['favorite'] },
  { shortcode: 'heart', emoji: '❤️', tags: ['love', 'red'] },
  { shortcode: 'orange_heart', emoji: '🧡' },
  { shortcode: 'yellow_heart', emoji: '💛' },
  { shortcode: 'green_heart', emoji: '💚' },
  { shortcode: 'blue_heart', emoji: '💙' },
  { shortcode: 'purple_heart', emoji: '💜' },
  { shortcode: 'broken_heart', emoji: '💔' },
  { shortcode: '100', emoji: '💯', tags: ['perfect', 'score'] },
  { shortcode: 'tada', emoji: '🎉', tags: ['party', 'celebrate'] },
  { shortcode: 'confetti_ball', emoji: '🎊' },
  { shortcode: 'balloon', emoji: '🎈' },
  { shortcode: 'gift', emoji: '🎁' },
  { shortcode: 'trophy', emoji: '🏆', tags: ['win', 'award'] },
  { shortcode: 'medal', emoji: '🏅' },
  { shortcode: 'muscle', emoji: '💪', tags: ['strong', 'flex'] },
  { shortcode: 'clap', emoji: '👏', tags: ['applause'] },
  { shortcode: 'raised_hands', emoji: '🙌', tags: ['celebrate'] },
  { shortcode: 'pray', emoji: '🙏', tags: ['thanks', 'please'] },
  { shortcode: 'thumbsup', emoji: '👍', tags: ['+1', 'yes'] },
  { shortcode: 'thumbsdown', emoji: '👎', tags: ['-1', 'no'] },
  { shortcode: 'wave', emoji: '👋', tags: ['hello'] },
  { shortcode: 'eyes', emoji: '👀', tags: ['look', 'see'] },
  { shortcode: 'thinking', emoji: '🤔', tags: ['hmm'] },
  { shortcode: 'sweat_smile', emoji: '😅' },
  { shortcode: 'joy', emoji: '😂', tags: ['lol', 'funny'] },
  { shortcode: 'rofl', emoji: '🤣' },
  { shortcode: 'smile', emoji: '😄' },
  { shortcode: 'grin', emoji: '😁' },
  { shortcode: 'wink', emoji: '😉' },
  { shortcode: 'heart_eyes', emoji: '😍' },
  { shortcode: 'sunglasses', emoji: '😎', tags: ['cool'] },
  { shortcode: 'cry', emoji: '😢' },
  { shortcode: 'sob', emoji: '😭' },
  { shortcode: 'rage', emoji: '😡', tags: ['angry'] },
  { shortcode: 'skull', emoji: '💀', tags: ['dead'] },
  { shortcode: 'ghost', emoji: '👻' },
  { shortcode: 'alien', emoji: '👽' },
  { shortcode: 'robot', emoji: '🤖' },
  { shortcode: 'warning', emoji: '⚠️', tags: ['alert', 'caution'] },
  { shortcode: 'exclamation', emoji: '❗', tags: ['important'] },
  { shortcode: 'question', emoji: '❓' },
  { shortcode: 'information_source', emoji: 'ℹ️', tags: ['info'] },
  { shortcode: 'link', emoji: '🔗', tags: ['url', 'chain'] },
  { shortcode: 'paperclip', emoji: '📎', tags: ['attach'] },
  { shortcode: 'pushpin', emoji: '📌', tags: ['pin'] },
  { shortcode: 'round_pushpin', emoji: '📍' },
  { shortcode: 'memo', emoji: '📝', tags: ['note', 'write'] },
  { shortcode: 'pencil', emoji: '✏️' },
  { shortcode: 'book', emoji: '📖' },
  { shortcode: 'books', emoji: '📚' },
  { shortcode: 'bookmark', emoji: '🔖' },
  { shortcode: 'chart_with_upwards_trend', emoji: '📈', tags: ['growth'] },
  { shortcode: 'chart_with_downwards_trend', emoji: '📉' },
  { shortcode: 'bar_chart', emoji: '📊' },
  { shortcode: 'calendar', emoji: '📅' },
  { shortcode: 'clock', emoji: '⏰', tags: ['time', 'alarm'] },
  { shortcode: 'hourglass', emoji: '⏳' },
  { shortcode: 'email', emoji: '📧', tags: ['mail'] },
  { shortcode: 'envelope', emoji: '✉️' },
  { shortcode: 'incoming_envelope', emoji: '📨' },
  { shortcode: 'telephone', emoji: '☎️', tags: ['phone'] },
  { shortcode: 'computer', emoji: '💻', tags: ['laptop', 'pc'] },
  { shortcode: 'keyboard', emoji: '⌨️' },
  { shortcode: 'mouse', emoji: '🖱️' },
  { shortcode: 'printer', emoji: '🖨️' },
  { shortcode: 'camera', emoji: '📷' },
  { shortcode: 'video_camera', emoji: '📹' },
  { shortcode: 'microphone', emoji: '🎤' },
  { shortcode: 'headphones', emoji: '🎧' },
  { shortcode: 'bell', emoji: '🔔', tags: ['notification'] },
  { shortcode: 'mute', emoji: '🔇' },
  { shortcode: 'loudspeaker', emoji: '📢' },
  { shortcode: 'mag', emoji: '🔍', tags: ['search', 'zoom'] },
  { shortcode: 'mag_right', emoji: '🔎' },
  { shortcode: 'lock', emoji: '🔒', tags: ['secure'] },
  { shortcode: 'unlock', emoji: '🔓' },
  { shortcode: 'key', emoji: '🔑' },
  { shortcode: 'hammer', emoji: '🔨', tags: ['tool', 'build'] },
  { shortcode: 'wrench', emoji: '🔧', tags: ['fix', 'tool'] },
  { shortcode: 'gear', emoji: '⚙️', tags: ['settings', 'config'] },
  { shortcode: 'nut_and_bolt', emoji: '🔩' },
  { shortcode: 'package', emoji: '📦', tags: ['box', 'ship'] },
  { shortcode: 'truck', emoji: '🚚', tags: ['delivery'] },
  { shortcode: 'airplane', emoji: '✈️', tags: ['flight'] },
  { shortcode: 'car', emoji: '🚗' },
  { shortcode: 'bus', emoji: '🚌' },
  { shortcode: 'train', emoji: '🚆' },
  { shortcode: 'bike', emoji: '🚲' },
  { shortcode: 'walking', emoji: '🚶' },
  { shortcode: 'runner', emoji: '🏃', tags: ['run'] },
  { shortcode: 'soccer', emoji: '⚽' },
  { shortcode: 'basketball', emoji: '🏀' },
  { shortcode: 'football', emoji: '🏈' },
  { shortcode: 'tennis', emoji: '🎾' },
  { shortcode: 'coffee', emoji: '☕' },
  { shortcode: 'beer', emoji: '🍺' },
  { shortcode: 'wine_glass', emoji: '🍷' },
  { shortcode: 'pizza', emoji: '🍕' },
  { shortcode: 'hamburger', emoji: '🍔' },
  { shortcode: 'fries', emoji: '🍟' },
  { shortcode: 'cake', emoji: '🎂' },
  { shortcode: 'cookie', emoji: '🍪' },
  { shortcode: 'apple', emoji: '🍎' },
  { shortcode: 'banana', emoji: '🍌' },
  { shortcode: 'grapes', emoji: '🍇' },
  { shortcode: 'watermelon', emoji: '🍉' },
  { shortcode: 'sunflower', emoji: '🌻' },
  { shortcode: 'herb', emoji: '🌿', tags: ['plant', 'leaf'] },
  { shortcode: 'four_leaf_clover', emoji: '🍀', tags: ['luck'] },
  { shortcode: 'evergreen_tree', emoji: '🌲' },
  { shortcode: 'deciduous_tree', emoji: '🌳' },
  { shortcode: 'cactus', emoji: '🌵' },
  { shortcode: 'tulip', emoji: '🌷' },
  { shortcode: 'cherry_blossom', emoji: '🌸' },
  { shortcode: 'rose', emoji: '🌹' },
  { shortcode: 'hibiscus', emoji: '🌺' },
  { shortcode: 'sun_with_face', emoji: '🌞', tags: ['sunny'] },
  { shortcode: 'full_moon', emoji: '🌕' },
  { shortcode: 'cloud', emoji: '☁️' },
  { shortcode: 'rainbow', emoji: '🌈' },
  { shortcode: 'umbrella', emoji: '☔' },
  { shortcode: 'snowflake', emoji: '❄️', tags: ['cold', 'winter'] },
  { shortcode: 'zap', emoji: '⚡', tags: ['lightning', 'fast'] },
  { shortcode: 'boom', emoji: '💥', tags: ['explosion'] },
  { shortcode: 'droplet', emoji: '💧', tags: ['water'] },
  { shortcode: 'ocean', emoji: '🌊', tags: ['wave', 'sea'] },
  { shortcode: 'earth_americas', emoji: '🌎', tags: ['world', 'globe'] },
  { shortcode: 'globe_with_meridians', emoji: '🌐' },
  { shortcode: 'flag_white', emoji: '🏳️' },
  { shortcode: 'checkered_flag', emoji: '🏁', tags: ['finish'] },
  { shortcode: 'triangular_flag_on_post', emoji: '🚩' },
];

export function searchEmojiCatalog(query: string, limit = 80): EmojiEntry[] {
  const q = query.trim().toLowerCase().replace(/^:/, '');
  if (!q) return EMOJI_CATALOG.slice(0, limit);
  return EMOJI_CATALOG.filter((e) => {
    if (e.shortcode.includes(q)) return true;
    return e.tags?.some((t) => t.includes(q));
  }).slice(0, limit);
}

export function findEmojiByShortcode(shortcode: string): EmojiEntry | undefined {
  const key = shortcode.toLowerCase().replace(/^:|:$/g, '');
  return EMOJI_CATALOG.find((e) => e.shortcode === key);
}
