export const Error = {
  NET_ERR: 'Please check your internet connection and try again!',
}
export const Authentication = {
  Login: "Please sign in to your admin account!",
  ForgetPassword: "Forgot Password ?",
  ForgetText:
    " Please enter your registered email address to receive an Link for resetting your password.",
  Verify: "Verify your account",
  VerifyText: "We’ve sent an OTP to admin@ulearn.com",
  VText: "Please enter it below to reset the password.",
  ResendOtp: "Resend OTP in",
  GoBack: "Go back to",
  CreatePassword: "Create new password",
  CreateText: "Please set a new password for your account.",
  CreatePasswordButton: "Set password & Sign in",
  SignIn: "Sign in",
  Submit: "Submit",
};
export const SidebarTitle = {
  Dashboard: "Dashboard",
  UserManagement : "User Management",
  ActivityManagement : "Activity Management",
  Sparks : "Sparks",
  CityInquiries : "City Inquiries",
  Master: "Master",
  Vendor: "Vendor Categories",
  Age: "Age Groups",
  Class: "Classes & Subjects",
  Academic: "Academic Years",
  Activity: "Activity Configurations",
  Schools: "Schools",
  Teachers: "Teachers",
  Students: "Students",
  Vendors: "Vendors",
  AboutUs: "About us",
  Privacy: "Privacy Policy",
  Terms: "Terms & Conditions",
  Settings: "Settings",
  faqs : "FAQs",
  contactUs : "Contact us",
  SurveyQuestion : "Survey Question"
};
export const UserString = {
  Title: "Users",
  AddButton: "Add User",
  TitleAdd: "Add School",
  filterBy: "Filter by",
  srNo: "Sr No",
  locationName: "location Name",
  adminName: "Admin Name",
  email: "Email",
  viewDetails: "View Details",
  noData: "No Data Found",
  edit: "Edit school",
  delete: "Delete school",
  teachersCount: "Teachers Count",
  joiningDate: "Joining Date",
  UserProfile: "User Profile",
  Activity : "Total Activitys",
  UserName : "User Name",
  location : "Location",
  PhoneNumber: "Phone Number",
  age : "Age",
  language : "Language",
  gender : "Gender",
  occupation : "Occupation"
}
export const ActivityString = {
  Title : "Activity",
  activityTitle : "Activity title",
  CreatorName : "Creator Name",
  DateTime : "Date and time",
  location : "Location",
  participantsCount : "Participants Count",
  status : "Status",
  filterBy: "Filter by",
  viewDetails: "View Details",
  noData: "No Data Found",
  edit: "Edit Activity",
  delete: "Delete Activity",
  ActivityProfile: "Activity Profile",
}
export const SparksString = {
  title : "Sparks",
  filterBy: "Filter by",
  SparksType : "Sparks type",
  DateAdded : "Date Added",
  UsageCount : "Usage Count",
  Status : "Status",
  noData: "No Data Found",
  SparksProfile: "Sparks Profile",
}
export const CityInquiriesString = {
  title : "City Inquiries",
  city: "City",
  country : "Country",
  date : "Date",
  userEmail : "User Email",
  noData: "No Data Found",
  viewTopcity : "View top 5 cities"
}
export const cmsString = {
  aboutUsTitle: "Add / Edit About us",
  termsTitle: "Add / Edit Terms and conditions",
  privacyTitle: "Add / Edit Privacy policy",
  save: "Save details",
};
export const faqString = {
  faq: 'FAQs',
  search: 'Search...',
  question: 'Question',
  answer: 'Answer',
  addMoreFaq: 'Add more FAQs',
  edit: 'Edit FAQ',
  delete: 'Delete FAQ',
  modalTitle: 'Frequently asked question!',
  save: 'Save changes',
  pleaseWait : "Please wait..."
};
export const ContactString = {
  title: 'Contact Enquiries',
  searchPlaceholder: 'Search by customer name…',
  viewProfile: 'View profile',
  delete: 'Delete this enquiry',
  viewMessage: 'View message',
  name: 'Name',
  receivedOn: 'Received on',
};
export const userString = {
  Title: "Vendors",
  BusinessName: "Business Name",
 
  VendorsDetails: "Vendors Details",
  AddButton: "Add Vendor",
  Category: "Category",
  Leads: "Leads",
  Viewers: "Viewers",
  Filterbykeyword: "Filter by keyword",
  Filterbycategory: "Filter by category",
  FilterbySubCategory: "Filter by SubCategory",
  edit: "Edit vendor",
  delete: "Delete vendor",
  AddVendor: "Add Vendor",
  Submit: "Submit",
  uploadPhoto: "upload Photo",
  ManageProfile: "Manage profile",
  editVendor: "Edit Vendor",
  BannerImage: "Banner Image",
  ProfileImage: "Profile Image",
  BasicDetails: "Basic details",
  VendorName: "Vendor name",
  Email: "Email",
  Address: "Address",
  SelectCategory: "Select category",
  SubCategory: "Sub category",
  Cancel: "Cancel",
  SaveChanges: "Save changes",
  UserProfile: "Vendor Profile",
  leads: "Total leads",
  views: "Total views",
  totalServices: "Total Services",
  view: "View Details",
  BuildingNumber: "Building Number",
  // tasks : "task"
};


export const CMS_MSG = {
    termsOfService: "Terms and conditions updated successfully!",
    privacyPolicy: "Privacy and policy updated successfully!",
    appSettings: "App settings updated successfully!",
    aboutUs: "About us updated successfully !",
};

export const commonString = {
    phone: "Phone Number",
    email: "Email",
    noDataFound: "No Data Found.",
    saveChanges: "Save Changes",
    name: "Name",
    filterByDates: "Filter by Dates",
    filterByStatus: "Filter by Status",
    viewAll: "View All",
    noDataAvailable: "No details available for these dates.",
    notSupported: "Your browser does not support the video tag.",
    pleaseWait: "Please wait...",
    cancel: "Cancel",
    appSettings: "App Settings",
    androidVersion: "Android Version",
    iosVersion: "iOS Version",
    androidForce: "Android Force Update",
    iosForce: "iOS Force Update",
    iosMaintain: "iOS App Maintenance",
    androidMaintain: "Android App Maintenance",
    update: "Update",
};